version: '3.8'

services:
  db-backup-server:
    build: .
    container_name: db-backup-server
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./backups:/app/backups
    environment:
      - NODE_ENV=production
